## **Tugas 2 : Pre-processing dan TFIDF**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/PPW/tugas2/data_berita.csv")
df.head()

,judul,tanggal,isi,kategori
0,"Apriyani Rahayu Sudah Berlatih Lagi, Ingin Com...","Rabu, 06 Nov 2024 15:25 WIB",Jakarta - Atlet bulutangkis Indonesia Apriyani...,Olahraga
1,Hasil Korea Masters 2024: Putri KW Lanjut ke 1...,"Rabu, 06 Nov 2024 14:36 WIB",Jakarta - Putri Kusuma Wardani hadapi wakil Ta...,Olahraga
2,Fajar/Rian di Japan dan China Masters: Inginny...,"Rabu, 06 Nov 2024 14:13 WIB",Jakarta - Fajar Alfian/Muhammad Rian Ardianto ...,Olahraga
3,Hasil Korea Masters 2024: Komang Ayu Tersingkir,"Rabu, 06 Nov 2024 12:45 WIB",Jakarta - Komang Ayu Cahya Dewi hadapi Liang T...,Olahraga
4,Korea Masters 2024 Hari Kedua: Tiga Wakil RI B...,"Rabu, 06 Nov 2024 10:55 WIB",Jakarta - Turnamen Korea Masters 2024 memasuki...,Olahraga

### ***Cleansing***

Cleansing adalah proses pengolahan data yang bertujuan untuk menghilangkan noise, error, atau data yang tidak relevan dari data yang telah dikumpulkan. Proses cleansing ini dilakukan untuk meningkatkan kualitas data dan memudahkan analisis dan pengolahan data.

Cleansing dapat dilakukan dengan cara mengidentifikasi dan menghapus data yang tidak relevan, seperti:

1. Data yang tidak sesuai dengan kriteria penelitian
2. Data yang terdiri dari noise, seperti tanda baca atau karakter yang tidak sesuai
3. Data yang memiliki error, seperti typo atau kesalahan dalam penginputan
4. Data yang tidak dapat diolah, seperti data yang tidak dapat diinterpretasikan

Cleansing dapat dilakukan dengan cara menggunakan algoritma-algoritma tertentu, seperti:

1. Algoritma filtering: Algoritma ini digunakan untuk menghilangkan data yang tidak relevan dengan cara mengidentifikasi dan menghapus data yang tidak sesuai dengan kriteria penelitian.
2. Algoritma cleaning: Algoritma ini digunakan untuk menghilangkan noise dan error dari data dengan cara mengidentifikasi dan menghapus data yang tidak sesuai dengan kriteria penelitian.
3. Algoritma normalization: Algoritma ini digunakan untuk menghilangkan data yang tidak sesuai dengan kriteria penelitian dengan cara mengnormalisasi data menjadi bentuk yang sama.

Cleansing memiliki beberapa tujuan, seperti:

1. Meningkatkan kualitas data: Cleansing dapat meningkatkan kualitas data dengan cara menghilangkan noise, error, dan data yang tidak relevan.
2. Memudahkan analisis: Cleansing dapat memudahkan analisis dengan cara menghilangkan data yang tidak relevan dan mengnormalisasi data menjadi bentuk yang sama.
3. Meningkatkan efisiensi: Cleansing dapat meningkatkan efisiensi dalam pengolahan data dengan cara menghilangkan data yang tidak relevan dan mengnormalisasi data menjadi bentuk yang sama.

Namun, cleansing juga memiliki beberapa kelemahan, seperti:

1. Kesulitan dalam mengidentifikasi data yang tidak relevan: Cleansing dapat sulit dalam mengidentifikasi data yang tidak relevan, sehingga dapat menghasilkan kesalahan dalam analisis.
2. Kesulitan dalam mengatasi noise: Cleansing dapat sulit dalam mengatasi noise, seperti tanda baca yang tidak sesuai dengan data yang akan diolah.
3. Kesulitan dalam mengatasi error: Cleansing dapat sulit dalam mengatasi error, seperti typo atau kesalahan dalam penginputan.

Dalam keseluruhan, cleansing adalah proses yang sangat berguna dalam pengolahan data, dan dapat digunakan untuk berbagai tujuan, seperti analisis sintaks, analisis semantik, dan lain-lain.

In [ ]:
import re
import string
import nltk

# Fungsi ini bertujuan untuk menghapus URL dari teks.
def remove_url(ulasan):
  url = re.compile(r'https?://\S+|www\.S+')
  return url.sub(r'', ulasan)

# Fungsi ini bertujuan untuk menghapus tag HTML dari teks.
def remove_html(ulasan):
  html = re.compile(r'<.#?>')
  return html.sub(r'', ulasan)

# Fungsi ini bertujuan untuk menghapus emoji dari teks.
def remove_emoji(ulasan):
  emoji_pattern = re.compile("["
      u"\U0001F600-\U0001F64F"
      u"\U0001F300-\U0001F5FF"
      u"\U0001F680-\U0001F6FF"
      u"\U0001F1E0-\U0001F1FF""]+", flags=re.UNICODE)
  return emoji_pattern.sub(r'', ulasan)

# Fungsi ini bertujuan untuk menghapus angka dari teks.
def remove_numbers(ulasan):
  ulasan = re.sub(r'\d+', '', ulasan)
  return ulasan


# Fungsi ini bertujuan untuk menghapus simbol dari teks, menyisakan hanya huruf, angka, dan spasi.
def remove_symbols(ulasan):
  ulasan = re.sub(r'[^a-zA-Z0-9\s]', '', ulasan)
  return ulasan

df['cleansing'] = df['isi'].apply(lambda x: remove_url(x))
df['cleansing'] = df['cleansing'].apply(lambda x: remove_html(x))
df['cleansing'] = df['cleansing'].apply(lambda x: remove_emoji(x))
df['cleansing'] = df['cleansing'].apply(lambda x: remove_symbols(x))
df['cleansing'] = df['cleansing'].apply(lambda x: remove_numbers(x))

df.head(5)

,judul,tanggal,isi,kategori,cleansing
0,"Apriyani Rahayu Sudah Berlatih Lagi, Ingin Com...","Rabu, 06 Nov 2024 15:25 WIB",Jakarta - Atlet bulutangkis Indonesia Apriyani...,Olahraga,Jakarta Atlet bulutangkis Indonesia Apriyani ...
1,Hasil Korea Masters 2024: Putri KW Lanjut ke 1...,"Rabu, 06 Nov 2024 14:36 WIB",Jakarta - Putri Kusuma Wardani hadapi wakil Ta...,Olahraga,Jakarta Putri Kusuma Wardani hadapi wakil Tai...
2,Fajar/Rian di Japan dan China Masters: Inginny...,"Rabu, 06 Nov 2024 14:13 WIB",Jakarta - Fajar Alfian/Muhammad Rian Ardianto ...,Olahraga,Jakarta Fajar AlfianMuhammad Rian Ardianto be...
3,Hasil Korea Masters 2024: Komang Ayu Tersingkir,"Rabu, 06 Nov 2024 12:45 WIB",Jakarta - Komang Ayu Cahya Dewi hadapi Liang T...,Olahraga,Jakarta Komang Ayu Cahya Dewi hadapi Liang Ti...
4,Korea Masters 2024 Hari Kedua: Tiga Wakil RI B...,"Rabu, 06 Nov 2024 10:55 WIB",Jakarta - Turnamen Korea Masters 2024 memasuki...,Olahraga,Jakarta Turnamen Korea Masters memasuki hari...

### ***Case Folding***

Case folding adalah proses pengkonversian teks menjadi bentuk yang sama, baik huruf besar atau huruf kecil, untuk memudahkan analisis dan pengolahan teks. Case folding dilakukan dengan cara mengkonversi semua huruf besar menjadi huruf kecil atau sebaliknya.

Contoh:

* "Hello" menjadi "hello"
* "HELLO" menjadi "hello"
* "HeLlO" menjadi "hello"

Case folding memiliki beberapa tujuan, seperti:

1. Memudahkan analisis teks: Case folding memudahkan analisis teks dengan cara mengkonversi semua huruf besar menjadi huruf kecil, sehingga dapat diolah dengan lebih mudah.
2. Meningkatkan efisiensi: Case folding dapat meningkatkan efisiensi dalam pengolahan teks dengan cara mengurangi ukuran data yang perlu diolah.
3. Meningkatkan akurasi: Case folding dapat meningkatkan akurasi dalam analisis teks dengan cara mengkonversi semua huruf besar menjadi huruf kecil, sehingga dapat diolah dengan lebih akurat.

Case folding dapat dilakukan dengan cara menggunakan algoritma-algoritma tertentu, seperti:

1. Algoritma simple: Algoritma ini mengkonversi semua huruf besar menjadi huruf kecil dengan cara mengganti semua huruf besar dengan huruf kecil.
2. Algoritma complex: Algoritma ini mengkonversi semua huruf besar menjadi huruf kecil dengan cara mengganti semua huruf besar dengan huruf kecil, dan juga mengkonversi semua huruf kecil menjadi huruf besar.

Case folding memiliki beberapa kelebihan, seperti:

1. Memudahkan analisis teks: Case folding memudahkan analisis teks dengan cara mengkonversi semua huruf besar menjadi huruf kecil.
2. Meningkatkan efisiensi: Case folding dapat meningkatkan efisiensi dalam pengolahan teks dengan cara mengurangi ukuran data yang perlu diolah.
3. Meningkatkan akurasi: Case folding dapat meningkatkan akurasi dalam analisis teks dengan cara mengkonversi semua huruf besar menjadi huruf kecil.

Namun, case folding juga memiliki beberapa kelemahan, seperti:

1. Kesulitan dalam mengidentifikasi huruf besar dan huruf kecil: Case folding dapat sulit dalam mengidentifikasi huruf besar dan huruf kecil, sehingga dapat menghasilkan kesalahan dalam analisis teks.
2. Kesulitan dalam mengatasi noise: Case folding dapat sulit dalam mengatasi noise, seperti tanda baca yang tidak sesuai dengan huruf besar dan huruf kecil.

Dalam keseluruhan, case folding adalah proses yang sangat berguna dalam pengolahan teks, dan dapat digunakan untuk berbagai tujuan, seperti analisis sintaks, analisis semantik, dan lain-lain.

In [ ]:
def case_folding(text):
    if isinstance(text, str):
      lowercase_text = text.lower()
      return lowercase_text
    else :
      return text

df ['case_folding'] = df['cleansing'].apply(case_folding)

df.head(5)

,judul,tanggal,isi,kategori,cleansing,case_folding
0,"Apriyani Rahayu Sudah Berlatih Lagi, Ingin Com...","Rabu, 06 Nov 2024 15:25 WIB",Jakarta - Atlet bulutangkis Indonesia Apriyani...,Olahraga,Jakarta Atlet bulutangkis Indonesia Apriyani ...,jakarta atlet bulutangkis indonesia apriyani ...
1,Hasil Korea Masters 2024: Putri KW Lanjut ke 1...,"Rabu, 06 Nov 2024 14:36 WIB",Jakarta - Putri Kusuma Wardani hadapi wakil Ta...,Olahraga,Jakarta Putri Kusuma Wardani hadapi wakil Tai...,jakarta putri kusuma wardani hadapi wakil tai...
2,Fajar/Rian di Japan dan China Masters: Inginny...,"Rabu, 06 Nov 2024 14:13 WIB",Jakarta - Fajar Alfian/Muhammad Rian Ardianto ...,Olahraga,Jakarta Fajar AlfianMuhammad Rian Ardianto be...,jakarta fajar alfianmuhammad rian ardianto be...
3,Hasil Korea Masters 2024: Komang Ayu Tersingkir,"Rabu, 06 Nov 2024 12:45 WIB",Jakarta - Komang Ayu Cahya Dewi hadapi Liang T...,Olahraga,Jakarta Komang Ayu Cahya Dewi hadapi Liang Ti...,jakarta komang ayu cahya dewi hadapi liang ti...
4,Korea Masters 2024 Hari Kedua: Tiga Wakil RI B...,"Rabu, 06 Nov 2024 10:55 WIB",Jakarta - Turnamen Korea Masters 2024 memasuki...,Olahraga,Jakarta Turnamen Korea Masters memasuki hari...,jakarta turnamen korea masters memasuki hari...

### ***Tokenization***

Tokenization adalah proses pengkonversian teks menjadi unit-unit kecil yang disebut token. Token dapat berupa kata, frasa, atau karakter individu. Tujuan dari tokenization adalah untuk memudahkan analisis dan pengolahan teks, seperti analisis sintaks, analisis semantik, dan lain-lain.

Tokenization dilakukan dengan cara mengidentifikasi unit-unit kecil dalam teks, seperti:

1. Kata-kata: Tokenization dapat dilakukan dengan cara mengidentifikasi kata-kata individu dalam teks, seperti "hello", "world", dan lain-lain.
2. Frasa-frasa: Tokenization dapat dilakukan dengan cara mengidentifikasi frasa-frasa dalam teks, seperti "hello world", "this is a test", dan lain-lain.
3. Karakter-karakter: Tokenization dapat dilakukan dengan cara mengidentifikasi karakter-karakter individu dalam teks, seperti "a", "b", "c", dan lain-lain.

Tokenization dapat dilakukan dengan cara menggunakan algoritma-algoritma tertentu, seperti:

1. Algoritma whitespace: Algoritma ini menggunakan spasi sebagai batas antara token-token.
2. Algoritma punctuation: Algoritma ini menggunakan tanda baca sebagai batas antara token-token.
3. Algoritma regex: Algoritma ini menggunakan regular expression untuk mengidentifikasi token-token.

Tokenization memiliki beberapa kelebihan, seperti:

1. Memudahkan analisis teks: Tokenization memudahkan analisis teks dengan cara mengkonversikan teks menjadi unit-unit kecil yang lebih mudah diolah.
2. Meningkatkan efisiensi: Tokenization dapat meningkatkan efisiensi dalam pengolahan teks dengan cara mengurangi ukuran data yang perlu diolah.
3. Meningkatkan akurasi: Tokenization dapat meningkatkan akurasi dalam analisis teks dengan cara mengkonversikan teks menjadi unit-unit kecil yang lebih mudah diolah.

Namun, tokenization juga memiliki beberapa kelemahan, seperti:

1. Kesulitan dalam mengidentifikasi token-token: Tokenization dapat sulit dalam mengidentifikasi token-token yang tidak jelas, seperti kata-kata yang terdiri dari lebih dari satu kata.
2. Kesulitan dalam mengatasi noise: Tokenization dapat sulit dalam mengatasi noise, seperti tanda baca yang tidak sesuai dengan token-token.

Dalam keseluruhan, tokenization adalah proses yang sangat berguna dalam pengolahan teks, dan dapat digunakan untuk berbagai tujuan, seperti analisis sintaks, analisis semantik, dan lain-lain.

In [ ]:
def tokenize(text):
    tokens = text.split()
    return tokens

df['tokenize'] = df['case_folding'].apply(tokenize)

df.head(5)

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize
0,"Apriyani Rahayu Sudah Berlatih Lagi, Ingin Com...","Rabu, 06 Nov 2024 15:25 WIB",Jakarta - Atlet bulutangkis Indonesia Apriyani...,Olahraga,Jakarta Atlet bulutangkis Indonesia Apriyani ...,jakarta atlet bulutangkis indonesia apriyani ...,"[jakarta, atlet, bulutangkis, indonesia, apriy..."
1,Hasil Korea Masters 2024: Putri KW Lanjut ke 1...,"Rabu, 06 Nov 2024 14:36 WIB",Jakarta - Putri Kusuma Wardani hadapi wakil Ta...,Olahraga,Jakarta Putri Kusuma Wardani hadapi wakil Tai...,jakarta putri kusuma wardani hadapi wakil tai...,"[jakarta, putri, kusuma, wardani, hadapi, waki..."
2,Fajar/Rian di Japan dan China Masters: Inginny...,"Rabu, 06 Nov 2024 14:13 WIB",Jakarta - Fajar Alfian/Muhammad Rian Ardianto ...,Olahraga,Jakarta Fajar AlfianMuhammad Rian Ardianto be...,jakarta fajar alfianmuhammad rian ardianto be...,"[jakarta, fajar, alfianmuhammad, rian, ardiant..."
3,Hasil Korea Masters 2024: Komang Ayu Tersingkir,"Rabu, 06 Nov 2024 12:45 WIB",Jakarta - Komang Ayu Cahya Dewi hadapi Liang T...,Olahraga,Jakarta Komang Ayu Cahya Dewi hadapi Liang Ti...,jakarta komang ayu cahya dewi hadapi liang ti...,"[jakarta, komang, ayu, cahya, dewi, hadapi, li..."
4,Korea Masters 2024 Hari Kedua: Tiga Wakil RI B...,"Rabu, 06 Nov 2024 10:55 WIB",Jakarta - Turnamen Korea Masters 2024 memasuki...,Olahraga,Jakarta Turnamen Korea Masters memasuki hari...,jakarta turnamen korea masters memasuki hari...,"[jakarta, turnamen, korea, masters, memasuki, ..."

### ***Stopword Removal***

Stopword removal adalah proses penghapusan kata-kata yang tidak berarti atau tidak penting dalam teks, seperti kata-kata yang berfungsi sebagai konjungsi, preposisi, atau kata-kata yang tidak memiliki arti yang jelas. Kata-kata ini disebut stopwords.

Stopwords dapat mengganggu analisis teks, karena mereka dapat membuat teks menjadi tidak jelas atau sulit dipahami. Oleh karena itu, stopwords harus dihapus dari teks sebelum melakukan analisis.

Contoh stopwords:

* Konjungsi: and, but, or, yet
* Preposisi: of, in, on, at
* Kata-kata yang tidak memiliki arti: a, an, the, is, are, am
* Kata-kata yang berfungsi sebagai konjungsi: however, therefore, thus

Stopword removal dapat dilakukan dengan cara menggunakan algoritma-algoritma tertentu, seperti:

1. Algoritma list-based: Algoritma ini menggunakan daftar stopwords yang telah ditentukan sebelumnya untuk menghapus stopwords dari teks.
2. Algoritma machine learning: Algoritma ini menggunakan machine learning untuk mengidentifikasi stopwords dan menghapus mereka dari teks.
3. Algoritma natural language processing: Algoritma ini menggunakan teknologi natural language processing untuk mengidentifikasi stopwords dan menghapus mereka dari teks.

Stopword removal memiliki beberapa tujuan, seperti:

1. Meningkatkan kualitas analisis: Stopword removal dapat meningkatkan kualitas analisis teks dengan cara menghilangkan kata-kata yang tidak berarti atau tidak penting.
2. Meningkatkan efisiensi: Stopword removal dapat meningkatkan efisiensi dalam pengolahan teks dengan cara menghilangkan kata-kata yang tidak berarti atau tidak penting.
3. Meningkatkan akurasi: Stopword removal dapat meningkatkan akurasi dalam analisis teks dengan cara menghilangkan kata-kata yang tidak berarti atau tidak penting.

Namun, stopword removal juga memiliki beberapa kelemahan, seperti:

1. Kesulitan dalam mengidentifikasi stopwords: Stopword removal dapat sulit dalam mengidentifikasi stopwords, sehingga dapat menghasilkan kesalahan dalam analisis.
2. Kesulitan dalam mengatasi kata-kata yang memiliki arti yang jelas: Stopword removal dapat sulit dalam mengatasi kata-kata yang memiliki arti yang jelas, sehingga dapat menghasilkan kesalahan dalam analisis.

Dalam keseluruhan, stopword removal adalah proses yang sangat berguna dalam pengolahan teks, dan dapat digunakan untuk berbagai tujuan, seperti analisis sintaks, analisis semantik, dan lain-lain.

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = stopwords.words('indonesian')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
def remove_stopwords(text):
  return [word for word in text if word not in stop_words]

df['stopword_removal'] = df['tokenize'].apply(lambda x: ' '.join(remove_stopwords(x)))

df.head(5)

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal
0,"Apriyani Rahayu Sudah Berlatih Lagi, Ingin Com...","Rabu, 06 Nov 2024 15:25 WIB",Jakarta - Atlet bulutangkis Indonesia Apriyani...,Olahraga,Jakarta Atlet bulutangkis Indonesia Apriyani ...,jakarta atlet bulutangkis indonesia apriyani ...,"[jakarta, atlet, bulutangkis, indonesia, apriy...",jakarta atlet bulutangkis indonesia apriyani r...
1,Hasil Korea Masters 2024: Putri KW Lanjut ke 1...,"Rabu, 06 Nov 2024 14:36 WIB",Jakarta - Putri Kusuma Wardani hadapi wakil Ta...,Olahraga,Jakarta Putri Kusuma Wardani hadapi wakil Tai...,jakarta putri kusuma wardani hadapi wakil tai...,"[jakarta, putri, kusuma, wardani, hadapi, waki...",jakarta putri kusuma wardani hadapi wakil taiw...
2,Fajar/Rian di Japan dan China Masters: Inginny...,"Rabu, 06 Nov 2024 14:13 WIB",Jakarta - Fajar Alfian/Muhammad Rian Ardianto ...,Olahraga,Jakarta Fajar AlfianMuhammad Rian Ardianto be...,jakarta fajar alfianmuhammad rian ardianto be...,"[jakarta, fajar, alfianmuhammad, rian, ardiant...",jakarta fajar alfianmuhammad rian ardianto ber...
3,Hasil Korea Masters 2024: Komang Ayu Tersingkir,"Rabu, 06 Nov 2024 12:45 WIB",Jakarta - Komang Ayu Cahya Dewi hadapi Liang T...,Olahraga,Jakarta Komang Ayu Cahya Dewi hadapi Liang Ti...,jakarta komang ayu cahya dewi hadapi liang ti...,"[jakarta, komang, ayu, cahya, dewi, hadapi, li...",jakarta komang ayu cahya dewi hadapi liang tin...
4,Korea Masters 2024 Hari Kedua: Tiga Wakil RI B...,"Rabu, 06 Nov 2024 10:55 WIB",Jakarta - Turnamen Korea Masters 2024 memasuki...,Olahraga,Jakarta Turnamen Korea Masters memasuki hari...,jakarta turnamen korea masters memasuki hari...,"[jakarta, turnamen, korea, masters, memasuki, ...",jakarta turnamen korea masters memasuki penyel...

In [ ]:
df.to_csv("/content/drive/My Drive/PPW/tugas2/hasil_prepros.csv",encoding='utf8', index=False)

### ***Term Frequency-Inverse Document Frequency (TF-IDF)***

TF-IDF (Term Frequency-Inverse Document Frequency) adalah suatu metode yang digunakan untuk menghitung pentingnya suatu kata dalam suatu dokumen. Metode ini menghitung frekuensi kata dalam suatu dokumen (Term Frequency) dan juga menghitung frekuensi kata dalam semua dokumen lainnya (Inverse Document Frequency). Dengan demikian, TF-IDF dapat digunakan untuk menghitung pentingnya suatu kata dalam suatu dokumen dan juga untuk menghitung relevansi suatu kata dengan suatu topik.

In [ ]:
import pandas as pd

data = pd.read_csv("/content/drive/My Drive/PPW/tugas2/hasil_prepros.csv", sep=",")

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Menginisialisasi TfidfVectorizer
vectorizer = TfidfVectorizer()

# Menghitung TF-IDF
tfidf_matrix = vectorizer.fit_transform(df['stopword_removal'])

In [ ]:
# Mengubah hasilnya menjadi DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df.head(10)

,abadi,abdul,abs,absen,absennya,ac,acara,accident,accu,aceh,...,yuan,yuhsun,yuni,yusuf,yzrm,zarco,zenix,zero,zf,zhi
0,0.0,0.0,0.0,0.052251,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.250595,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
2,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
3,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
5,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.068146
6,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
7,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
8,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
9,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [ ]:
import pickle

# Simpan tfidf_matrix dan vectorizer ke dalam file pickle
with open('/content/drive/My Drive/PPW/tugas2/tfidf_matrix.pkl', 'wb') as file:
    pickle.dump(tfidf_matrix, file)

with open('/content/drive/My Drive/PPW/tugas2/vectorizer.pkl', 'wb') as file:
    pickle.dump(vectorizer, file)